name: curl_logger_dio_interceptor
description: Get your http requests printed as curl command in your terminal. Share them easily with your colleagues and import them in Postman!
version: 1.0.1
homepage: https://github.com/OwnWeb/curl_logger_dio_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.1.1

dev_dependencies:
  flutter_lints: ^1.0.4
