name: curl_logger_dio_interceptor
description: Get your http requests printed as curl command in your terminal. Share them easily with your colleagues and import them in Postman!
version: 0.0.1+2
homepage: https://github.com/OwnWeb/curl_logger_dio_interceptor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^4.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
